### ISSUE TITLE
The possibility of a plugin to support .lottie

### ISSUE THREAD

**Issue by Fz0011** [aojiaoxiaolinlin/swf_animation#1]
This is amazing! now I can use .swf! However I’d like to make a request/suggestion: would it be possible for you to port .lottie to Godot? Unfortunately, something like this would require knowledge of Rust, and I wasn’t able to accomplish it due to my lack of experience with the language.

.lottie-dotlottie is similar to .swf in that it’s a format containing animations, JSON, state machines, and interactivity. It’s supported by ThorVG (a vector graphics rendering engine) which is already integrated into Godot. It could also be feasible to integrate an open-source Rust library like [dotlottie-rs](https://github.com/LottieFiles/dotlottie-) to render .lottie animations while maintaining the scalability and flexibility of SVG rendering.

Here you can have more details about: [Proposal For .lottie in godot](https://github.com/godotengine/godot-proposals/issues/9104)

This could be incredibly useful for both UIs and in-game content with dynamic scaling capabilities. I understand this may not be directly related to your plugin, so I apologize for any issues. Thank you for your time and attention!

**Comment by aojiaoxiaolinlin** [comment]
I'm very sorry, I don't have enough energy to implement this function. In fact, I am not familiar with Godot, and I don't even know C++. Currently, SWF animation is also extracted texture, not vector rendering.
